# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

# This is commented out, so that developers can iterate on the
# webhook without the checked in version clobbering their PAT!
# apiVersion: v1
# kind: Secret
# metadata:
#   name: github-token
# stringData:
#   # Change this to a personal access token with "repo" permissions.
#   pat: FILL ME IN!
