# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

# This is commented out, so that developers can iterate on the
# webhook without the checked in version clobbering their webhook!
# apiVersion: v1
# kind: Secret
# metadata:
#   name: slack
# stringData:
#   # Change this to a Slack webhook url.
#   webhook: FILL ME IN!
